### ISSUE TITLE
K8S Config Hint

### ISSUE THREAD

**Issue by rdrrichards** [rdrrichards/QIQO.Business.Next#30]
```
spec:
    containers:
        - name: chachacha
          image: imagename
          imagePullPolicy: IfNotPresent <--- *The hint*
```
