### ISSUE TITLE
K8S Cluster IP Service for APIs

### ISSUE THREAD

**Issue by rdrrichards** [rdrrichards/QIQO.Business.Next#31]
```
---
apiVersion: v1
kind: Service
metadata:
  name: commands-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: commandservice
  ports:
  - name: commandservice
    protocol: TCP
    port: 80
    targetPort: 80 
```
